name: appost
description: Posting app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #  di
  get_it: ^4.0.1
  injectable: ^0.3.0
  # network
  retrofit: ^1.3.3
  json_serializable: ^3.3.0
  connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4
  logger: ^0.8.3
  pretty_dio_logger: ^1.1.1
  dio_retry: ^0.1.9-beta
  # state management
  provider: ^4.0.5
  # navigation
  auto_route: ^0.4.4
  # util
  freezed_annotation: ^0.7.1
  shared_preferences: ^0.5.6+3
  flushbar: ^1.10.0
  flutter_svg: ^0.17.4
  email_validator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  # di
  injectable_generator: ^0.3.4
  # network
  retrofit_generator: ^1.3.3
  # navigation
  auto_route_generator: ^0.4.4
  # util
  freezed: ^0.10.6

flutter:

  uses-material-design: true

  assets:
    - lang/
    - fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/Oswald/Oswald-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Oswald/Oswald-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Oswald/Oswald-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Oswald/Oswald-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/Oswald/Oswald-Bold.ttf
          style: normal
          weight: 700
